language: ruby

matrix:
  include:
    - os: osx
      osx_image: xcode8

before_install:
  - bundle install
  - brew install swiftlint

before_script:
  - match development
  - match appstore
  
after_success:
  - bash < (curl -s https://codecov.io/bash)

branches:
  only:
    - release

script:
  fastlane beta
  swiftlint
