language: ruby

matrix:
  include:
    - os: osx
      osx_image: xcode8.2

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage swiftlint
  - gem install fastlane

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

branches:
  only:
    - release
    - dev

script:
  - fastlane beta
