language: ruby

matrix:
  include:
    - os: osx
      osx_image: xcode8
      env:
        - DISPLAY=:99.0

before_install:
  - bundle install

branches:
  only:
    - master



script: 
  match development && match appstore && fastlane beta
