language: ruby

matrix:
  include:
    - os: osx
      osx_image: xcode8

before_install:
  - brew install carthage
  - bundle install

before_script:
  - match development
  - match appstore

after_success:
  - bash < (curl -s https://codecov.io/bash)

branches:
  only:
    - release
    - dev

script:
  - carthage build --platform iOS
  - fastlane beta
  - swiftlint
