language: ruby

matrix:
  include:
    - os: osx
      osx_image: xcode8

before_script:
  - carthage bootstrap --platform iOS
  - match development
  - match appstore

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - bundle install

before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

branches:
  only:
    - release
    - dev

script:
  - fastlane beta
  - swiftlint
