update_fastlane
fastlane_version "1.106.2"

default_platform :ios

platform :ios do
  before_all do
    ENV["CRASHLYTICS_NOTES"] = changelog_from_git_commits
  end

  desc "Runs all the tests"
  lane :test do
    scan(
      scheme: "OctoPhone"
    )
  end

  desc "Submit a new Beta Build to Crashlytics"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    carthage(
      use_binaries: true,
      platform: "iOS"
    )
    swiftlint
    scan(
      scheme: "OctoPhone"
    )
    create_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"],
      password: ENV["MATCH_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )
    match(
      type: "development",
      keychain_name: ENV["MATCH_KEYCHAIN_NAME"],
      keychain_password: ENV["MATCH_PASSWORD"],
      readonly: true
    )
    increment_version_number
    gym
    xcov
    crashlytics
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    carthage(
      use_binaries: true,
      platform: "iOS"
    )
    swiftlint
    scan(
      scheme: "OctoPhone"
    )
    create_keychain(
      name: ENV["MATCH_KEYCHAIN_NAME"],
      password: ENV["MATCH_PASSWORD"],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true
    )
    # match(type: "appstore")
    # snapshot
    gym
    # deliver(force: true)
    # frameit
  end

  desc ""
  after_all do |lane|
    slack(
      message: "Successfully deployed new App Update."
    )
  end

  error do |lane, exception|
    slack(
      message: exception.message,
      success: false
    )
  end
end
